spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:icarenow
    driverClassName: org.h2.Driver
    username: adi
    password: adi
  h2.console.enabled: true
#logging.level.root: DEBUG
#logging.level.org.springframework: DEBUG